language: node_js
node_js:
    - "6.2.2"
git:
  submodules: false
install:
    - npm install
test:
    - npm run test
services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS USER;'
    - mysql -e 'use USER;create table User('tingbaobao',''litingting', 22, 'nv',  15829348754, '1766153116@qq.com', '')'

